### ISSUE TITLE
Package symbolix.utils?

### ISSUE THREAD

**Issue by ghost** [SymbolixAU/spatialdatatable#6]
Your [code](https://github.com/SymbolixAU/spatialdatatable/blob/master/vignettes/spatialdatatable.Rmd) refers to package symbolix.utils - where can I find this package in order to get the function mapKey?

```mapKey <- symbolix.utils::mapKey()```

**Comment by SymbolixAU** [comment]
You can't, it's a private package. 
If you want to use `googleway` you'll need your own Google Maps API key anyway
