### ISSUE TITLE
symbolix.utils::mapKey()

### ISSUE THREAD

**Issue by ghost** [SymbolixAU/spatialdatatable#7]
Your [code](https://github.com/SymbolixAU/spatialdatatable/blob/master/vignettes/spatialdatatable.Rmd) refers to package symbolix.utils - where can I find this package in order to get the function mapKey?

```mapKey <- symbolix.utils::mapKey()```

If the package is closed and not available, you should introduce an example that uses publicly accessible information for your examples, or state upfront that your package is not intended for public use.

**Comment by SymbolixAU** [comment]
closed in https://github.com/SymbolixAU/spatialdatatable/commit/3c6b7df897e100d4637df2d834bab3e8492734be
